services:
  - type: web
    name: depression-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    region: us
    instances: 1
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
